# Generated by Django 5.2.7 on 2025-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(),
        ),
    ]
